### ISSUE TITLE
[Feature Request] Check packages.xml inode and trigger rescan of apps only if file changed

### ISSUE THREAD

**Issue by sn-o-w** [NeoApplications/Neo-Backup#496]
Hi there,

I saw this Magisk commit: https://github.com/topjohnwu/Magisk/commit/4c80808997e392667d80bcc53da9e59d547913a7

And I was wondering... Can't you do something similar to OABX? 🤔

John Wu checks packages.xml inode. If the /data/system/packages.xml hasn't changed, it doesn't trigger the rescan of all apps every time you open Magisk.

But it looks like this happens on OABX. I have a physical Android device with Magisk and OABX installed, a Nexus 5. And it takes a while until I see all the apps since I opened OABX. I didn't install a new app nor did I delete any app for weeks, maybe months...

So this could be useful for slower/older devices, perhaps? 😊

**Comment by machiav3lli** [comment]
Hey, thanks for this and the email, sorry I somehow forgot to write you back. The slow initialization for the most part doesn't have to do with the packages' list rather with reading the backups data from the disk using SAF. I'm already working on a database caching to allow at least accessing unupdated data at start. Suggestions are nevertheless always welcome.

**Comment by hg42** [comment]
I think it's a good suggestion. Thanks.

May be it doesn't work in all variants of ROMs and devices etc. It depends on what exactly how the file is handled and may be some mount options (though this should only affect access time).

My observations (see the toast when the list loads) seem to suggest that the main time is used by asking the package manager and building the installed packages list ("packages" toast).
Though this is weird.
Sometimes the "all" toast (which includes the packages time) takes a very long time.
Sometimes you see multiple "all" toasts, but not always...not sure how I should interpret this.
It looks much like it's called multiple times in parallel. I feel that it is triggered by remaining work items.
(btw. this could be tested by enabling cancelOnStart, which removes all work hopefully before it starts any actions)

E.g. usually I have 20 sec for installed "packages" and 2-3 secs additionally for "all".
Often the time is very long, e.g. 100 secs.
So, it's not clear who is taking the time.
Using RootFile instead of SAF doesn't change the general behavior.

**Comment by hg42** [comment]
btw. we could touch a file in the backup directory for each change, or even maintain a central file containing everything we need to know about the directory.
Basically all property files in one.

**Comment by hg42** [comment]
I'll asd the path here for the record:
`/data/system/packages.xml`

**Comment by hg42** [comment]
after some months, the picture is different:

Reading packages from the system isn't a problem at all.

Nearly all of the duration is consumed by scanning the backups.
This has become a lot faster already.

There is still room for improvement.
The main one is putting all backups at the top level directory (which I started lately).
This should help, because SAF seems to be very slow in reading directory contents.
Finding all backup properties in one directory scan should be much better than reading each package directory.
We will see soon.
