### ISSUE TITLE
Decrypting files under Linux/Windows

### ISSUE THREAD

**Issue by andrei-a-papou** [NeoApplications/Neo-Backup#527]
I need this feature for contingency and I'm trying to put together a Python script that would accomplish this. I'd be happy to share the script and put together a HOWTO if this works.

I'm OK with Python, but not experienced with cryptography. I've looked at https://github.com/NeoApplications/Neo-Backup/blob/main/app/src/main/java/com/machiav3lli/backup/utils/CryptoUtils.kt and done some research, but have some questions and would appreciate some help from someone who understand encryption much better than I do -- as well as OAndBackupX specifics:

1. What items do I need to decrypt an archive encrypted with AES-GCM? Just the password and the IV, correct? Or I also need the original salt (seems to be stored in [encrypted preferences](https://github.com/NeoApplications/Neo-Backup/blob/bee23171beaac044bcb34e2b8371d832a9c4709c/app/src/main/java/com/machiav3lli/backup/utils/PrefUtils.kt))? If so, how can I know what it is?
2. Is the IV stored in the archive? If so, is it prepended and what is its length? The recommended length is 12 bytes, but the [source code](https://github.com/NeoApplications/Neo-Backup/blob/main/app/src/main/java/com/machiav3lli/backup/utils/CryptoUtils.kt) seems to suggest 32 bytes?
3. Is the authentication tag 16 bytes and is it appended at the end of the archive?

I've also tried various tools like [LibreSSL](https://www.libressl.org/) (OpenSSL doesn't support AES-GCM via CLI) and [OABXDecrypt](https://github.com/Tiefkuehlpizze/OABXDecrypt/releases/tag/1.0.0) (this one is horrible for security because the password is visible under process list) -- but with no success (tag authentication error). 

My draft Python code can encrypt and decrypt arbitrary files using AES-GCM-256, but fails to decrypt OAndBackupX's archives (the error is 'invalid tag', same as with other tools). I think the IV and/or tag offsets are wrong and I'm not decrypting the right cypher text as a result.

Any help is much appreciated!

**Comment by Tiefkuehlpizze** [comment]
Hi, I've updated [OABXDecrypt](https://github.com/Tiefkuehlpizze/OABXDecrypt) to address your security concerns. I hope it's better now.

Unfortunately, I cannot tell you much more about decrypting the data as you're already on a very advanced research state. But addition information to address your questions:

1. You need 3 things to setup the decryption module:
  - The 16 byte _IV_ from the backup's properties file
  - The salt which is usually "oandbackupx" as bytes (using UTF-8 encoding) (see [CryptoUtils.kt](https://github.com/NeoApplications/Neo-Backup/blob/8bfea5f4a91846f0d7c7788e97238ce90c194bac/app/src/main/java/com/machiav3lli/backup/utils/CryptoUtils.kt#L50)
  - The _256_ bit key derived from _salt_ and _password_ using _PBKDF2withHmacSHA256_ using _2020_ iterations
 2. The IV is stored on the backup's properties file and has 16 bits. The data stream is just the (gzipped) tar archive.
 3. I'm not sure about this one, but as far as I could figure it out: Yes, the `doFinal()` call done by the `close()` method of a CipherOutputStream calls it internally causing the cipher to process the buffer and thus it can append whatever it needs. After a short search, how the ciphers are defined in jdk, I traced it down to `jdk.crypto.cryptoki/sun/security/pkcs11/SunPKCS11.java` and then `java.base/sun/security/ssl/SSLCipher.java` where it became complicated. But I hope as user of encryption, your library handles this. NB doesn't append any extra data. I've added a check for `AEADBadTagException` into OABXDecrypt, because it usually indicates a wrong password. I hope this helps you.

**Comment by Tiefkuehlpizze** [comment]
Regarding your Python issue and question 3:
I have an encrypted input file with 752 bytes and I wrote a small Python script using `Crypto.Cipher.AES` and `hashlib.pbkdf2_hmac`. At least my first observation was that OABXDecrypt's output was only 736 bytes after decrypting. So there are 16 bytes extra at the end. This is the authentication tag. The Java lib seems to do the check internally while Python's Crypto lib wants you to do it explicitly.

Here's a short code doing the decryption in Python (I like how short and easy it is):
```python
import json
import os
from Crypto.Cipher import AES
from hashlib import pbkdf2_hmac

BACKUP_STAMP = '2022-04-20-22-59-54-061-user_0'
INPUT_FILEPATH = os.path.join(BACKUP_STAMP, 'data.tar.gz.enc')
PASSWORD = b'123456'
PBKDF_ITERATIONS = 2022
KEY_LEN = 32
FALLBACK_SALT = b'oandbackupx'

with open(BACKUP_STAMP + '.properties') as f:
    properties = json.load(f)
    iv_bytes = b''.join(map(lambda i: int(i).to_bytes(1, 'big', signed=True), properties['iv']))

key = pbkdf2_hmac(hash_name='sha256',
                  password=PASSWORD,
                  salt=, FALLBACK_SALT,
                  iterations=PBKDF_ITERATIONS,
                  dklen=KEY_LEN)
cipher = AES.new(key, AES.MODE_GCM, nonce=iv_bytes)
with open(INPUT_FILEPATH, 'rb') as input_file:
    with open(os.path.splitext(INPUT_FILEPATH)[0], 'wb') as output_file:
        buffer_in = input_file.read()[:-16]
        buffer_out = cipher.decrypt(buffer_in)
        output_file.write(buffer_out)
```

**Comment by Tiefkuehlpizze** [comment]
My fault: `read -s NB_PASSWORD` reads a value into a variable, but does not make it available as environment variable. What's missing is `export NB_PASSWORD` after the read call.

**Comment by andrei-a-papou** [comment]
@Tiefkuehlpizze Your comments are very helpful, thank you! Turns out I was pretty close, but I missed the properties file and kept looking for IV in the archive itself.

I think you've solved the issue, both in Java and Python! Thanks again, I hope it keeps working with upcoming 8.0 release :)

**Comment by andrei-a-papou** [comment]
https://github.com/Tiefkuehlpizze/OABXDecrypt seems to work fine for v7.0.0 backups, I'll do more testing and re-open if something goes wrong.

**Comment by andrei-a-papou** [comment]
thanks for the update, @machiav3lli!
