### ISSUE TITLE
[Feature Request] Backed up files should be invisible to other apps

### ISSUE THREAD

**Issue by stearless** [NeoApplications/Neo-Backup#570]
When I look for APK files in file manager a bunch of base.apk files and split apks appear from neobackup which is unnecessary, they are useless without Neobackup and therefore should be only visible within the app.

A simple hidden folder might fix the issue

**Screenshots**
![Screenshot_20220604-110851.jpg](https://user-images.githubusercontent.com/105450109/171992648-2560c5d9-1451-44c4-8e41-c25220370a46.jpg)

**System Information:**

- Device: OnePlus 7 Pro
- Android Version: 11
- ROM: OOS
- App Version: 8.0.2

**Comment by hg42** [comment]
I would say, it's a problem of the file manager.
If an app searches the whole storage for apks it only logically that all apks are found.
NB cannot know how another app searches, e.g. the file manager could also scan hidden folders (btw. what do you mean by "hidden"? marked with .nomedia? or using a folder starting with a dot? as you see it's not really defined).
In case you mean .nomedia, then simply add the file to the the backup folder. Though I doubt the file manager will respect that (it would if it would use media storage).

**Comment by stearless** [comment]
Just tested it, hiding the main folder hides it from NeoBackup as well,
which is not a valid solution then I guess.

**Comment by MrEngineerMind** [comment]
I am not an expert with android storage, but I believe Android 11+ (non-rooted) makes it virtually impossible for other apps to access ("see") files in another app's "Internal" memory.

So maybe NB could offer the option to store the backups in "External" memory (as it does now) or "Internal" memory (that only NB can access), which will hide it from other apps - even a file manager if the device is not rooted (because file managers on rooted devices can see pretty much any file).

**Comment by stearless** [comment]
Yeah, I meant hidden folder, it doesn't respect .nomedia, but it does
respect hidden folders, I'm not sure if NeoBackup would have issues if the
backup remained hidden?
So the solution is either the whole folder is hidden or each folder
containing an apk file be hidden.

**Comment by hg42** [comment]
there are several ways to hide a folder.
I unix the standard is to start the name with a dot.

.folder

I just tried it with both SAF and shadowRoot and NB seems to work.

I think the SAF part ignores it, and I guess the su commands also do.

What happens when your file manager hides a directory, I don't know.
It certainly depends on the purpose if hiding.
Who should not see the files?

E.g. the .nomedia marker file hides directories from media scanner, which affects all apps that use it. A file manger usually ignores this (because it doesn't use that file access method).
However simple file managers for normal users might access files via the media scanner.
