### ISSUE TITLE
Regress. No backwards compatibility.

### ISSUE THREAD

**Issue by snooppr** [NeoApplications/Neo-Backup#626]
I tried to use different versions of OB 8+ with no success. A backup that was created with v7.0.0 is not restored (just an .apk with no data) in OB 8+. There are other unpleasant bugs since version 8, but live with them.

This is an issue mainly and for those who can't restore their past backup to the latest OB versions (look in TG for old, working OB versions).

Androidv9.
![1](https://user-images.githubusercontent.com/61022210/184296666-f6802d9d-4d9e-4caf-a22b-2f45d69ca0df.png)

I suggest that the developer update all posts in TG with previous versions: specify the OB version for each application.

**Comment by JohnCGH** [comment]
The screen shot seems to indicate you tried to restore an older version of an app on top of a higher version.

What happens if you uninstall the app completely, then try to restore a 7.x backup of that app using NeoBackup 8.1.1?

**Comment by machiav3lli** [comment]
If it's a downgrade of an app is what you mean (your text isn't that clear), then just go to settings > advanced > allow downgrading. And don't forget to report back!
Otherwise please try to make your issue more comprehensible.

**Comment by snooppr** [comment]
Yes, I have a checkmark "Allow version downgrade".
It doesn't solve the problem.  Applications (even without data) are not restored created in versions 7x version NB 8.1.1 android 9.
![Screenshot_20220824-095901_Neo_Backup](https://user-images.githubusercontent.com/61022210/186353358-9922d666-4992-4d95-92fd-c0a7f473c76f.png)

**Comment by snooppr** [comment]
If you delete the application, then there is no such error, there is an attempt to restore, but I waited 10 minutes and the application is still in the "restoring" status.  I just demolished everything and returned to version 7, where there are no these problems (restoring only apk, data recovery with a problem).  

In general, I am leaving this software for another analogue, so I need stability.  I will not unsubscribe on the problem anymore, you can close the problem when you see fit.

**Comment by MrEngineerMind** [comment]
The file format of the backups changed from 7.x to 8.x, so that could be causing a problems for you. I have restored some simple apps from version 7.x using 8.x with no problem.

So, maybe backing up all your apps in 8.x will make restores more reliable.

**Comment by hg42** [comment]
obviously the title is way too general.

The downgrade issue is discussed in different issue threads, search for "downgrade".

It's crucial, which parts are restored.
You don't give exact information, which does not help us to determine what us going wrong and how exactly it's "not working".

E.g. you cannot compare a v8 restore with all data to a v7 restore with "only apk".
I guess "only apk" will also work with v8 even from a v7 backup (unless it's a downgrade, which is prevented by the system).

Currently the main interesting info (or most probable reason) would be, if it fails because of external data/obb/media.
v8 versions restored the data with a wrong app user id, in cases where the directory isn't existing (e.g. after an uninstall).

What happens if you exclude external data/media/obb?

Also, disabling device protected data could help in some situations.

**Comment by hg42** [comment]
> returned to version 7, where there are no these problems (restoring only apk, data recovery with a problem)

with a problem?
or without a problem?

**Comment by hg42** [comment]
> A backup that was created with v7.0.0 is not restored (just an .apk with no data) in OB 8+

hmm, I read this again, looks like I didn't understand it at first (I'm not a native english reader):

so,
* you only restored apk with v8?
* it is rejected because it's a downgrade
* you do the same with v7 and it works?

I think, the algorithm didn't change in this case.

I think the option -d was added to the pm command if you enable the allow downgrade option.
So it should be like v7, if you disable it.
Note, in newer Android versions that downgrade option only works for debug apks.
But without that option I would guess a downgrade is even more forbidden.

If v7 can really downgrade, it would be weird.
Can you please confirm?
Note, uninstall and install again isn't a downgrade.
A downgrade is when a newer apk is still installed before the restore.

Another reason could be, that v8 is compiled for a newer target sdk than v7, e.g. the newer sdk could be more restrictive. But it's unlikely because the pm command should be independent of this.

**Comment by hg42** [comment]
correction: v7 also has the allowDowngrade option, so it seems to be exactly the same command.

current v8 versions add the installer package (-i) name and the --user option to limit the profile.

Do you use a work profile or Shelter or a similar isolation app?

**Comment by hg42** [comment]
v7.0.0
```
String.format(
    "cat \"${apkPath.absolutePath}\" | pm install%s -t -r%s%s -S ${apkPath.length()}", // TODO add --user $profilId
    if (basePackageName != null) " -p $basePackageName" else "",
    if (context.isRestoreAllPermissions) " -g" else "",
    if (context.isAllowDowngrade) " -d" else ""
)
```

v8.1.1
```
listOfNotNull(
    "cat", quote(apkPath.absolutePath),
    "|",
    "pm", "install",
    basePackageName?.let { "-p $basePackageName" },
    if (context.isRestoreAllPermissions) "-g" else null,
    if (context.isAllowDowngrade) "-d" else null,
    "-i ${OABX.prefString(PREFS_INSTALLER_PACKAGENAME, OABX.app.packageName)}",
    "-t",
    "-r",
    "-S", apkPath.length().toString(),
    "--user", profileId,
).joinToString(" ")
```

8.0.0-alpha9 would be the last without --user, but cannot handle v7 backups, which was first introduced in 8.0.0-alpha10.
8.0.0-alpha12 is the last without installer package name (-i), introduced in 8.0.3-beta1

**Comment by hg42** [comment]
how is the value of installer package name in NB settings?

**Comment by hg42** [comment]
> I tried to use different versions of OB 8+ with no success

so, which versions?

**Comment by hg42** [comment]
> If you delete the application, then there is no such error

as expected, because it's no downgrade in this case

> there is an attempt to restore, but I waited 10 minutes and the application is still in the "restoring" status

with which version?
you may disable NB settings / Advanced / developer settings / pauseApps, perhaps it's blocking too much.

Apart from that, with v7 backups, v8 uses more or less the old v7 implementation and this invokes several root commands for each file.
So, if there are many files, it can easily take half an hour... this was basically why I started contributing here and implementing it by using the tar command.
However, if you say v7 doesn't have such problems, it's using the same algorithm, so it should be such a big difference.
But it's unclear if v7 had problems with data restore or not.
