### ISSUE TITLE
[Feature Request] Please add "Sort by Install Date" in filter

### ISSUE THREAD

**Issue by MrEngineerMind** [NeoApplications/Neo-Backup#631]
**Is your feature request related to a problem? Please describe it.**
If would be nice to see my apps listed in a descending order by install date. This way I can see if any apps were installed (or updated) on my device without my permission.

Yes, the app will already notify me of any app updates, but it will only do this for apps that have a backup, not for apps without a backup.

**Comment by luckkmaxx** [comment]
Hi there! I think its usefull too. For the same reasons, and to keep track of recently installed apps.

**Comment by rezad1393** [comment]
sort by update time (also newly installed apps) is what I miss from titanium backup days.

**Comment by machiav3lli** [comment]
I still don't see why sorting is relevant when filtering is possible… what is the added value of sorting compared to the filter?

**Comment by machiav3lli** [comment]
Plus I think the issue is solved in the latest release that allows more control of filters and optional notification of new user apps.

**Comment by hg42** [comment]
> why sorting is relevant when filtering is possible

I install a lot of apps for test purposes (and test them for a while) and don't need a backup usually.
But sometimes I install apps for other purposes.
Sorting by installation date puts newly installed apps at the top.

Also, tests may show, that I want to keep an app.
Such successful tests are usually from apps installed lately.

Showing "new" apps in the updated apps button was something I implemented before (you didn't agree to that part).
In fact it was something, I only thought to be useful for normal users. Instead, for my handling it's not what I need (in that simple form). I always have lots of apps listed as "new".
I would need a mechanism, that detects, that I ignore them (= show them only once, which needs a persistent list of ignored new or updated apps, and an app must be revived on an update). So, alternatively dropping apps that are new for more than x days seems to be easier to implement and to explain (x should probably be configurable).

**Comment by rezad1393** [comment]
> I still don't see why sorting is relevant when filtering is possible… what is the added value of sorting compared to the filter?

well.... I move between ROMs a bit and moving the apps I use between then is the reason I use this app.
sometimes I install an app and I like it (so I dont uninstall it) and then I move to another ROM and because when I use backup it doesnt show them at the top I forget to back them up and lose them.

I know filtering exist and thank you for that but seeing newer apps (or more recently updated ones) at the top, makes things way easier.

is there a reason why you are against this? is it not doable? or is it because of less demand for it?
if it is the first I understand but if it is the second, the first thing I did when I had the titanium backup app (old and proprietary)  was that I would set sort as install date. 

it helps the users see what changed between using the app.
