### ISSUE TITLE
Compression level does not really matter

### ISSUE THREAD

**Issue by k2helix** [NeoApplications/Neo-Backup#660]
Hello. I've always used compression level 5 but last week changed it to 9. What I've noticed is that most backups' size is still the same, and some even larger, which I suppose it is because its data has increased.

However, for apps that I didn't use since the last backup, the size is still the same and hasn't changed at all

**Expected behavior**
There should be a noticeable difference between both backups

-----------------------------

**Additional Notes**

I think it could be a good idea to compress apk files too as sometimes it is what makes a backup bigger.

**Comment by MrEngineerMind** [comment]
It could be that some of the larger files are already compressed of that app (like resource files), and trying to recompress them could actually make it larger.

For the same reason I don't think the apk should be compressed.

**Comment by hg42** [comment]
I agree, already compressed data is probably the main reason.

Big data, that is more or less the one that matters in the sum, usually tends to be compressed.

Images like jpeg or videos are typically heavily compressed (like no more data entropy) and may even be bigger when compressed again.

Also, all the small files will be very ineffective, the higher compression rates need more data to determine the better compression.

I usually use level 1, because I don't see a big difference and it's faster. Even 0 isn't much bigger.
If you have limited storage space, I suggest finding a smaller set of backups instead.
E.g. it doesn't make sense to backup APKs of system apps, and many of them don't need their data.
Then a lot of apps doesn't have important data at all (e.g. everything you use with default settings).
Making schedules for these groups leads to much more reduction than compression rate.

**Comment by k2helix** [comment]
I see. Thanks for your replies! I'll try to minimize the amount of apps and data that I backup, thanks for the tip!
