### ISSUE TITLE
[Bug] (?) Scheduled jobs not executed

### ISSUE THREAD

**Issue by jochen-01** [NeoApplications/Neo-Backup#663]
**Description**
I have some backup jobs which shall be executed during the night when the phone is not used and connected with power outlet. 
These batch jobs are not executed. They are tested interactively with "start now" -- no problem.

**Steps To Reproduce**
1. define batch job
2. modify schedule to sometime when phone is not used
3. make sure that battery optimization for Neo Backup is disabled

**Expected behavior**
Nightly backup job should be executed

**System Information(please complete the following information):**

- Device: HTC U11
- Android Version: 8.0 (rooted)
- ROM: (AOSP, MIUI, OOS...) stock 
- App's Version: 8.1.3

**Comment by hg42** [comment]
try enabling `useAlarmClock` in
`NB / AdvancedPreferences / Developer Settings`

**Comment by jochen-01** [comment]
> try enabling useAlarmClock in NB / AdvancedPreferences / Developer Settings
Will do. Have not tried it 'till now because of "don't change unless a developer tells you to!"

I'll report if that helps (takes a few days).

**Comment by hg42** [comment]
I don't really think it will help, but it could.
depends on the reasons...

Basically, the methods are not very different (at least in current ROMs).
Not sure about older Androids...

I guess it's an app killer (battery saver), if you didn't install it yourself, then it may be part of the ROM.
The algorithm might act different if it sees an alarm clock bound to NB.

**Comment by hg42** [comment]
these apps do something all the time.
Depending on the enabled features they are registered to several events.

NB registers only an alarm (which is something similar to an alarm clock, but without appearing as a clock), and then it does nothing.

I admit, I don't know, how it's actually handled by the system and this changed a lot along Android versions.

Especially, if the service needs to actually run (=started but sleeping) or if it would be started by the system if it does not run. This might be a difference between alarm and alarm clock (maybe only on older Androids).

Though, in newer Androids, I cannot see a difference and I think there are users with A8 where it works. I guess, your ROM is aggressive killing background processes, in order to advertise better battery runtime values.

You could also try useExactAlarm instead of useAlarmClock. This is basically like the default but demands a more accurate timing (the other may be delayed several minutes). With a little luck, your ROM doesn't kill such services, either. Would be interesting to know if it makes a difference.

I suggest to try this app:
https://dontkillmyapp.com/
it might give you some hints
E.g. on my realme X2 / rmx1993 / AOSP / A10 all dots are where they should and only drift a bit at the lower part (8 hours)

**Comment by jochen-01** [comment]
> Though, in newer Androids, I cannot see a difference and I think there are users with A8 where it works. I guess, your ROM is aggressive killing background processes.

"In newer Androids (...)". That gives me some hope. Until now, with Android 8, I am using Titanium Backup. In preparation of a change to Android 11 I had to look for something else: Neo Backup. If there are no problems with scheduled backup jobs it's o.k.

> You could also try useExactAlarm instead of useAlarmClock. This is basically like the default but demands a more accurate timing (the other may be delayed several minutes). With a little luck, your ROM doesn't kill such services, either. Would be interesting to know if it makes a difference.

Thank you, will try.

> I suggest to try this app: https://dontkillmyapp.com/ it might give you some hints E.g. on my realme X2 / rmx1993 / AOSP / A10 all dots are where they should and only drift a bit at the lower part (8 hours)

There HTC earned a golden cup. ;-)

**Comment by jochen-01** [comment]
> You could also try useExactAlarm instead of useAlarmClock. This is basically like the default but demands a more accurate timing (the other may be delayed several minutes). With a little luck, your ROM doesn't kill such services, either. Would be interesting to know if it makes a difference.

"useExactAlarm" works. Nothing killed, backup takes place at scheduled time. I hope that it does not keep the phone vom entering doze mode?

**Comment by hg42** [comment]
nice to know, thanks for reporting

the docs say that exact alarm takes more battery.
I think the mode when apps sleep a while and are awaken all together (might be called doze mode, but I see this confused with other methods) isn't used for NB then. But it shouldn't matter, because NB does nothing in the background. So I think you won't notice it.
Doze mode is more affecting apps that do something all the time like reading sensors etc.

**Comment by jochen-01** [comment]
Hey, I have to decide between two trade offs? ;-)
1. Having an alarm clock icon in the message bar,
2. having the battery drained faster.
How can I see the amount of battery power used by this method? Is it reported as "used by Neo Backup"? Just to see if it matters.

**Comment by hg42** [comment]
I guess, you will not see any impact...
because of this:
> But it shouldn't matter, because NB does nothing in the background

just enable on or the other and compare, or see if you can  notice an enabled schedule at all (I guess not)

**Comment by jochen-01** [comment]
Thank you, will do.

**Comment by hg42** [comment]
> Hey, I have to decide between two trade offs? ;-)
> 
>     1. Having an alarm clock icon in the message bar,
> 
>     2. having the battery drained faster.
>        How can I see the amount of battery power used by this method? Is it reported as "used by Neo Backup"? Just to see if it matters.

3. upgrade ROM

**Comment by jochen-01** [comment]
> 3\. upgrade ROM
:-)
Sure. My decision to try Neo Backup is because of that. Planning to purchase a new phone I have to change over from Titanium Backup to a replacement. I think Neo Backup can be part of my next backup concept. The alarm issue is not a real problem. If I find out how to restore an app which is not installed I can check the final point.
