### ISSUE TITLE
[Bug] Google Docs scheduled backup ignores number of revisions

### ISSUE THREAD

**Issue by k2helix** [NeoApplications/Neo-Backup#664]
**Description**
While I have the number of backups revision set to 2, Google Docs seems to ignore this and can have infinite backups if it is a scheduled backup

**Steps To Reproduce**

1. Set the number of revisions to something
2. Do some scheduled backups that include Google Docs
3. See that old backups are not being deleted

**Expected behavior**
As with all the other apps, old backups should be deleted

**System Information(please complete the following information):**

- Android Version: 12.1
- ROM: LOS 19
- App's Version: 8.1.3

-----------------------------

**Additional Notes**

If you do a manual backup, all the old backups get deleted and the number of revisions is correct.

**Comment by hg42** [comment]
In general, this doesn't happen normally.

I first thought it has to do with backups being "invisible" to NB, which can eventually be caused by damaged backups, though I tried my best to avoid this situation.

If the backup is invisible, the count in the list and the app sheet should be correct.

I tested it with these three apps ("docs" may be ambiguous):

- "Docs" (com.google.android.apps.docs.editors.docs)
- "Drive" (com.google.android.apps.docs)
- "Sheets" (com.google.android.apps.docs.editors.sheets)

in the custom list of 3 similar schedules with a different time.

I executed them with my current code (as debuggable code), 3x manually and 3x automated (at the scheduled times in  a 5-minute raster).
I still had only 2 backups each.

I tested with 8.1.3 and this created more than 2, but only for Docs and Sheets.
Drive still has 2.

It seems like it hangs on the Docs app (in state "end", so the backup seems to be finished).
Clicking on the notification jumps to the app and the notification is gone, so the job seems to be really finished (otherwise it would be a persistent notification, that cannot be removed by clicking on it).

I can reproduce it with manual execution of the schedule.
I can also reproduce it with a batch (search "docs").

A batch with the current debug code works again.
So I think I should compile it as release.

**Comment by hg42** [comment]
I wonder if some things are different with pumpkin, too.
Because latest reports in the telegram group say pumpkin works where release didn't.
There is quite a long list of changes, but as far as I see, they are not significant in the backend area (though you never know, might be a small thing).

Pumpkin is compiled as release code, but without minify (I think this is only mangled symbols).
What if the code needs symbols at some places? or may be the mere existence of some symbols changes compilation? Wouldn't be the first time in my life that something like that would not work as designed.

The other possibility would be that the code is compiled different on f-droid.
Maybe if we do not have full version specifications for each library?

Btw. I compile pumpkins with a gradle shell command, ignoring all caching.
The debug code is started from Android Studio.
For the test I used the same apk but from the launcher, so not under debugger control.

Indeed pumprel (= pumpkin with minify, like release) doesn't work either.
I have some missing libraries in the minify step. But the apk is still produced...
I can confirm that it works in a single manual backup started from the app sheet.

and pumpkin works...

so I think we have a compilation problem or it's some optimizing going on with minify that matters

Minify does this (ordered by how critical it looks for me, from low to high):
https://developer.android.com/studio/build/shrink-code
* Obfuscation: shortens the name of classes and members
* Resource shrinking: removes unused resources
* Code shrinking (or tree-shaking): removes unused classes, fields, methods, and attributes
* Optimization: inspects and rewrites your code to further reduce the size of your app’s DEX files. For example, if R8 detects that the else {} branch for a given if/else statement is never taken, R8 removes the code for the else {} branch. To learn more, go to the section about [code optimization](https://developer.android.com/studio/build/shrink-code#optimization)

In general this shouldn't influence execution of normal code, unless the decisions are faulty.
The docs say it "safely" removes XXX.

The most interesting part is, that it's only happening with Docs and Sheets and at least Docs is also failing for @k2helix.
So it's probably not a hiccup because of special data someone might have.
May be the two packages have something in common.

Also, why does it work from the app sheet. The code is the same.

The preferences should work, because it works with other apps.
The same for execution environment or similar.

Scheduled and batch point to WorkManager.
But why does it work for other apps?
Timing could play a role, in case the job is killed before housekeeping takes place.
Those apps don't take very long.

**@k2helix did you use the default preference for the moment when the housekeeping is done?
is it before the backup or after?**
(Prefs / Service / at the end, Revision Cleanup time)

My test with 8.1.3 did cleanup before.
My current code has this removed, the cleanup happens after the backup.
So in my 8.1.3 test the job cannot be stopped before the celanup is done.

I'm out of ideas.

In the next days I'll compile the same code with minify but switching features off successively (though I only found isShrinkResources).
I would like to see, which is the critical one.

**Comment by hg42** [comment]
the resource shrinking does not matter

**Comment by hg42** [comment]
it gets even more weird...

if I do a batch in 8.1.3 with only Docs and Sheets, it works !!!
though it seems to delete the backups more slowly, not sure.

BUT, whenever I include Drive (all three combinations), it doesn't work.

**Comment by hg42** [comment]
8.2.0-alpha01 release or neo works

after that reinstalled 8.1.3 release and it still doesn't work

so wie have another weirdness:
8.1.3 release _doesn't work_
8.2.0-alpha01 release **works**
current pump**rel** _doesn't work_

**Comment by k2helix** [comment]
What do you mean with default preference? The number of revisions? (If yes, in my case it has been always 2).

In my case Sheets works fine, maybe because I have not used it for months and its last backup is from 16 October. 

I'll try excluding drive when I have time.

Thanks for your research!

**Comment by k2helix** [comment]
The preference is set to Before backup.

Note that the last backup of Sheets I have is from months ago, so maybe if it is backed up more it'll happen too.

I'll let you know when/if I do the backup excluding drive.

**Comment by hg42** [comment]
Because Sheets seems to behave differently, It would be nice, if you could also try a batch backup of

* Drive+Docs+Sheets (2x if the backup directory is fresh)
* Drive+Sheets
* Drive+Docs
* Docs+Sheets

to see, if the combinations are like they are here (otherwise the conclusions could be different).
So note, which combinations increase more than the limit and when they are correct, the last one will probably make all counts ok again.
If you don't want to disturb your real backups, you could use an extra backup directory for testing (with a limit of 1 to safe time).

**Comment by hg42** [comment]
this is still happening for 8.2.0 release from github.

**But now it also happens for the neo version in Telegram.**

I really hope this change means, that the debug version can reproduce this, too.
Will test this on Sunday, I hope.

A short summary, what happens:
* if GDrive is included, GDocs and GSheets ignore the backup limit (but GDrive respects it!)
* if GDrive is excluded, the counts are correct afterwards.

we are still searching for other apps that influence others like GDrive does...

I noticed, that I'm not sure, if I used the release from github or from fdroid in my 8.1.3 tests.

This should be strictly separated in this analysis, because it's an independent compilation.
E.g. it might have different libraries or library ways to compile them, even if the versions are the same.
I'm not aware which problems are to expect in the JVM world (me: more low level C++ etc. or high level ruby, etc. jvm is somewhere in between).

**Comment by hg42** [comment]
I tested 8.1.3 with github release (I had changed the filename to version + gh and installing from fdroid needs an uninstall because of the different signature).

Whike I had to uninstall, I started fdroid tests at 8.1.1 and it had the problem, too.
I'll plan to go down the versions, to find a change.

**Comment by hg42** [comment]
if there is some variation (if neo does it etc.), I guess it's time based.

I guess, I should add some log messages...
and I bet, it works with these murphystical 🎃.

A theory would be, that the housekeeping gets a copy of the current backup list and works on it, while the update changes the original list.

But why does it also happen, when housekeeping is done before the backup?

**Comment by k2helix** [comment]
I just tested it on latest F-droid (8.2.0) and this happened

- Batch backup Drive, Docs, Sheets and Slides: the number of revisions is ignored
- Same without Drive: works fine

Sorry for the late answer

**Comment by hg42** [comment]
which device and model do you use?

if it's timing based, this would probably matter.

My test device uses:

Qualcomm SDM730 Snapdragon 730G (8 nm)
Octa-core (2x2.2 GHz Kryo 470 Gold & 6x1.8 GHz Kryo 470 Silver)

**Comment by hg42** [comment]
8.0.0 release from github behaves like 8.1.3

7.0.0 release from github behaves similar,
but Google Drive also increases,
GMail also increases (manual from AppSheet, so without Drive included and no batch anyways),
another user package I tried (A Better Camera) respected the limit (with +1 offset),

I would guess, what we fixed from 7 to 8 only worked halfway

**Comment by hg42** [comment]
just tested it again on 8.3.1, and it seems to be solved...

@k2helix can you also test when 8.3.1 when it is available on fdroid?

**Comment by k2helix** [comment]
> just tested it again on 8.3.1, and it seems to be solved...
> (there is no explicit fix for it, all the other fixes seem to include this one)
> 
> @k2helix can you also test when 8.3.1 when it is available on fdroid?

My scheduled backup will run tomorrow, I'll let you know!

**Comment by k2helix** [comment]
I can confirm it works as intended now. Thanks!

**Comment by hg42** [comment]
thanks
