### ISSUE TITLE
[Bug] Clock com.android.deskclock is missing

### ISSUE THREAD

**Issue by powellnorma** [NeoApplications/Neo-Backup#710]
**Description**

com.android.deskclock is missing, and I did not find something abuot this in the FAQ nor other issues

**Steps To Reproduce**

1. Type 'Clock' or 'com.android.deskclock' in the search bar
2. No results

**Expected behavior**

Ability to backup the Alarms configured in the Clock app

**System Information(please complete the following information):**

- Android Version:  13
- App's Version:  8.2.5

**Comment by hg42** [comment]
find the icon of your clock in system settings / apps and check it's package name
(or maybe open app info via app drawer, if your launcher supports it, e.g. Nova does )

**Comment by powellnorma** [comment]
Hi, I think the package name is `com.android.deskclock`, unless I am missing something

**Comment by hg42** [comment]
well, do you think or did you check? I only base conclusions on facts.
It's quite possible, that your ROM has another clock with another package name, without "clock".
You didn't tell about your ROM, device etc. so everything is open...

if **I** enter "clock" in the search bar I get com.google.android.deskclock. So it works here.
Which is why I guess your ROM has a clock that is not called clock.
How is it called in system settings, Title and package name.

**Comment by powellnorma** [comment]
From the applist generated by Neo-Backup:
```
Clock: com.android.deskclock @ 13
```

It was also included in the 'custom list' button under the 'my schedule' menu. However when I searched it in the main screen ("Homepage") it was missing.

I cleared the apps data+cache, and now it does appear.

**Comment by hg42** [comment]
probably on the blocklist?

**Comment by powellnorma** [comment]
Yes, that seems likely - A confirmation makes sense
