### ISSUE TITLE
[Bug] backup stuck in 8.3

### ISSUE THREAD

**Issue by benoiton** [NeoApplications/Neo-Backup#729]
**Description**

Backup does not work anymore with 8.3.0.
Backup seems to start, but the progress bar in status bar shows no progression. After a while, all seems stuck. System begins to alert about non responding apps.

Backup is OK with 8.2.5. (before upgrade and after downgrade)

I did not see anything in logcat.

**Steps To Reproduce**

1. Install neobackup 8.3.0 from F-Droid
2. Create a planned backup (user apps, apk and all data)
3. Run it

**System Information(please complete the following information):**

- Device: herolte (Samsung Galaxy S7)
- Android Version: 9
- ROM: LineageOS 16
- App's Version: 8.3.0

**Comment by hg42** [comment]
I guess, you have many packages.

For unknown reasons (probably depending on library versions), the Android WorkManger now starts backups for all packages at once, while it was about number of cores backups in parallel before.

It was kind of invisible, because it's not the number of threads, but coroutines.

Depending on device, Android version, ROM, etc. each system can run a different number of coroutines in parallel without crawling.

The issue is already solved.
We now use a limited parallelism (can be changed via dev setting).
You can try the pinned alpha version in the Telegram group (or one of the pumpkin apks).

**Comment by benoiton** [comment]
Great! I will test that ASAP.
Thanks.

**Comment by benoiton** [comment]
I do confirm version 8.3.1 from F-Droid now works as expected for me.
:+1:

**Comment by hg42** [comment]
thanks
