### ISSUE TITLE
[Bug] "The filtered list is empty" (only) for Scheduled Backups

### ISSUE THREAD

**Issue by tomcat-xx** [NeoApplications/Neo-Backup#734]
**Description**
Since upgrade to 8.2.5 my scheduled backups don't work anymore. I'm only getting message in subject. When starting manually all is fine, list is not empty even when starting right after scheduled backup.

With 8.3.0 there was no change. I also tried to create new backup/selection, but with same result. After upgrading to 8.3.1 it worked once (for 3 different backups) and I thought it is solved. But last night I got it again.

My backups are scheduled only once a week, so there is something to backup every time.

- Device: Samsung Galaxy S20 5G
- Android Version: 13
- ROM: original (rooted)  
- App's Version: 8.3.1

**Comment by phyrz91** [comment]
I have the same error. Last version, Android 13, Xiaomi 12.

**Comment by hg42** [comment]
The schedule list should be completely independent of the backup directory, as it is created from the database.
As far as I remember, it doesn't take any backups into account. Entering a schedule might be another thing, because of the filter settings (but I think they don't take backups into account, the filter is not executed, only configured, other than in the filters in main/backup/restore tabs, where a count is shown at the top, when selecting a filter)

Prove: I just chose a remote directory and while it was still scanning (takes some minutes, laser beams rotating), I could easily (and fast) switch back and forth between schedule list and configuring a schedule and main tab.

The size of the apk or archive files doesn't have any influence on finding the backups, either, because NB is only reading directories and the properties files.

**Comment by tomcat-xx** [comment]
Thanks for explanations. Might help analysis if it happens again. As written, for me it is "solved", at least issue doesn't exist anymore. Maybe just because damaged file of older backup generation has been deleted automatically. So nothing that I can check now.

**Comment by hg42** [comment]
ok, so I close it for now

**Comment by GottemHams** [comment]
This is still/again an issue. It seems to be related to locking the app (`Device lock` feature), because I noticed after opening Neo that it very briefly shows the exact same message (`The filtered list is empty`) in the main app list. I disabled the lock and now my backups run correctly again. My guess is that locking Neo prevents all background/non-user interaction too, like having its very own scheduler fetch the app list. Running backups manually never resulted in issues, which makes sense because the app would need to be unlocked first anyway.

This may or may not be relevant for #759 as well, because I also often didn't get a notification about the backup result when the app lock was still enabled (implying the scheduler didn't get past the lock far enough to generate a notification).
