### ISSUE TITLE
[Bug] "Use session installer" should be off on Android 12 or lower

### ISSUE THREAD

**Issue by shaygover** [NeoApplications/Neo-Backup#738]
**Description**
When "Use session installer" is on backup is stuck on the first app.
**Steps To Reproduce**

1. Leave that setting on
2. Try to backup
3. Wait 2 hours
4. Nothing happens

**Expected behavior**
A backup will happen

**System Information(please complete the following information):**

- Device: Xiaomi Poco F1
- Android Version:  10
- ROM: lineageOS 17.1
- App's Version: 8.3.0

**Comment by hg42** [comment]
I cannot confirm this...
I have an AOSP A10 ROM and it works with session installer.
I never had hanging backups.

And there is another bigger point:

The only action, where this setting is used, is **restore** (which is absolutely logical, because installation happens on restore, not on backup).
You can search for pref_enableSessionInstaller, it is used only at one place in the sources, in `RestoreAppAction.kt`.

How did you test it?
Did you switch off session installer and it worked.
Did you also switch it on again and it failed again?
How often did you try back and forth?

If it is really reproducible, we might think again, though I don't see any way, how this could be related.

**Comment by shaygover** [comment]
I see. Tested once. Will reopen if I've time to check and it's reproducible.
