### ISSUE TITLE
Syncthing and AFWall+ background services killed even when blacklisted.

### ISSUE THREAD

**Issue by erahhal** [NeoApplications/Neo-Backup#777]
**Description**
Syncthing and AFWall+ background services crash during backup, even though they are blacklisted from backup.

**Steps To Reproduce**

1. Install Syncthing and AFWall+ and set them up so their background services are running.
2. Setup a backup in Neobackup.  Settings I'm using:
* Blacklist - Add AFWall+ and Syncthing
* App type: Only select "User Apps"
* Backup types: Select everything
* Launchable: Select "All Apps"
* Updated: Select "All Apps"
* Latest Backup : Select "All App"
* Enabled: Select "All Apps"
4. Click "Start now"
5. Note that both Syncthing and AFWall+ services crashed, with the UI in Syncthing reflecting the service is not running, and AFWall+ giving the error `Error applying iptables rules` when trying to restart.  Killing both apps and restarting them fixes the issue after each backup.

**Expected behavior**
Backups shouldn't kill background services, especially when the apps are black listed

**System Information(please complete the following information):**

- Device: Google Pixel 7 Pro 
- Android Version: 13
- ROM: LineageOS 20 + MicroG + Magisk
- App's Version: 8.3.2

**Comment by hg42** [comment]
NB does **not** kill anything on backup, only on restore (if enabled, which is the default).

Instead, in case "backupPauseApps" preference in enabled, NB uses the unix **STOP** signal on all processes that have files open in the app directories about to be backed up.

This does not kill the processes but only pause execution.
After the backup, it uses the **CONT** signal to continue those stopped processes.
STOP and CONT should generally work unless NB is also using those processes, which would give a dead lock.
System processes are excluded, and as far as I remember the handling is also limited to processes belonging to the app user of the app currently backed up.

There is an additional "backupSupendApps" preference (that is only active when "backupPauseApps" is also enabled), that would also suspend the app (via `pm suspend`). This should not affect the other apps in any way.

**If you are unsure, disable "backupPauseApps", then NB only does the backup without any handling of processes.**


Note, at least at this lower level, it's not easy to find the apps belonging to a process, and check if they are excluded. And it doesn't matter, because if they have files open in the app directory they need  to be stopped, otherwise they would write files that are currently archived. If backupPauseApps is active, you expect that files are not changed while storing. If you disable this, you take this possibility into account (e.g. eventually getting inconsistent backups).
Though, it doesn't seem to be a high risk in practice (concluding from the kind of reports we get).


Not sure, why your services are crashing (btw. are they really? there are several ways how they could "crash" or look like that).

It may be possible, that a service is observing signals and instead of ignoring those it do not want, it may crash instead (e.g. because it's an unexpected signal).
Java libraries are heavily exception based, so it is a very common problem, that developers overlook a possible exception (or miss catching all), but that's not NB's fault.
A similar situation could be, if the service has certain expectations, that are no more true, if the service is paused for some time. Again, the unexpected situation could cause an exception and if it is not catched/handled, the whole service is terminated.

**Comment by erahhal** [comment]
Amazing explanation, thank you. Based on your response, I looked at what files Syncthing and AFWall might be accessing that are also accesses by other apps. I removed one share and blacklisted one app for Syncthing, and blacklisted the AFWall Unlock Key app, which is almost certainly accessed by AFWall, and what do you know? It worked, neither app fails now!

Thank you!

**Comment by hg42** [comment]
I don't think a schedule is much different, when looking at the program logic.

However, a schedule is a service itself, and it is usually run in a much different system state.
E.g. the doze mode of Android pauses all services for some time and then wakes up all the sleeping services at once.
So, it might be a lot more probable that another service is active at the same time.

During the backup, I would
* use airplane mode or reduce networking to a minimum
* prevent any SyncThing actions (e.g. it's run conditions can use the network state)

**Comment by erahhal** [comment]
I think this was an issue with the particular build of LineageOS I was using, After a couple updates the problem went away. Feel free to close this if you wish.
