### ISSUE TITLE
[Bug] All backups failing

### ISSUE THREAD

**Issue by wastemans** [NeoApplications/Neo-Backup#783]
**Description**

All backups in my schedule are failing with this error:
```
is.xyz.mpv
package not processed: is.xyz.mpv :
java.lang.NullPointerException: file
NullPointerException
file
at android.net.Uri.fromFile(Uri.java:481)
at com.machiav3lli.backup.items.StorageFile.getUri(Unknown
Source:96)
at
com.machiav3lli.backup.items.StorageFile.getPath(Unknown
Source:10)
at com.machiav3lli.backup.items
```

**Steps To Reproduce**

1. Create a new job
2. User Apps, All backup types
3. Run manually or on a schedule
4. All fail after a few minutes.

**Expected behavior**
An additional backup is performed.

I suspected this to be a storage issue, but it's able to read the contents of the backup directory and its existing backups.
I cleared cache, data, no luck.
I uninstalled the app and reinstalled and built a new schedule, still the same error.

**System Information(please complete the following information):**

- Device: Asus Zenfone 7 Pro
- Android Version: 13
- ROM: OMNI Rom
- App's Version: version 8.3.2 / 8309

**Comment by hg42** [comment]
I guess the schedule is executed automatically (via schedule time).

do other kinds of backups work?

* manually executing the schedule ("play" button, or on the schedule sheet)
* in app sheet from main page
* as batch from backup page
* via context menu from main page)

Are the apps in the schedule of a specific kind (like only system, etc.) or do they have a high diversity?

Please create a support log (long press title, share support log).
It contains access tests (you could also have a look yourself), though there is no schedule specific test.

Please create a log of the backup.
If it's only about automatic schedules, then enable autoLogAfterSchedule.
Use long press title/prepare support to set useful options.

In general the logs are more useful, if you use the neo version, because it contains real names instead of "unknown source" and shortened names like "a" etc.)

**Comment by wastemans** [comment]
_do other kinds of backups work?_
None of these methods work.

_Are the apps in the schedule of a specific kind (like only system, etc.) or do they have a high diversity?_
It's all user apps, all backup types, and all fail.

I can see the log you're asking for but when I click "shareSupportLog" nothing happens?

**Comment by wastemans** [comment]
I am a fool!!

`mkdir: cannot create directory ‘!-LOGS’: No space left on device`
