### ISSUE TITLE
Ability to restore old apps on Android 14

### ISSUE THREAD

**Issue by buttercookie42** [NeoApplications/Neo-Backup#810]
On Android 14 it is necessary to pass the `--bypass-low-target-sdk-block` flag to `pm install` when attempting to install apps that are considered too old by Android (anything targetting lower than Android M).

**Comment by hg42** [comment]
I blindly implemented first parts of it:

* check if pm has the option in the help output
* if so add it to the pm install command

remaining questions:

* how is this used in the session installer? which of the commands should get that option?
* hopefully it does not hurt to use it on an apk that isn't old?

**Comment by buttercookie42** [comment]
My phone doesn't yet have Android 14, so I'm basing this only on looking at the source code, but

> check if pm has the option in the help output

… based [on that](https://cs.android.com/android/platform/superproject/main/+/main:frameworks/base/services/core/java/com/android/server/pm/PackageManagerShellCommand.java;drc=ff280d0e84e36046569023be5f55cf728e08c9cf), the flag hasn't been included in the help output, so the only criterion is whether the app is running on ≥ Android 14 (API 34) or not.

> how is this used in the session installer? which of the commands should get that option?

I guess `install-create`, given that the [flag gets added to the session parameters](https://cs.android.com/android/platform/superproject/main/+/main:frameworks/base/services/core/java/com/android/server/pm/PackageManagerShellCommand.java;l=3367;drc=ff280d0e84e36046569023be5f55cf728e08c9cf) just as usual.

> hopefully it does not hurt to use it on an apk that isn't old?

Again, based on reading the source the only it shouldn't affect anything else. [This](https://cs.android.com/search?q=bypass-low-target-sdk-block&sq=&ss=android%2Fplatform%2Fsuperproject%2Fmain:frameworks%2F) gets turned [into this](https://cs.android.com/search?q=INSTALL_BYPASS_LOW_TARGET_SDK_BLOCK&sq=&ss=android%2Fplatform%2Fsuperproject%2Fmain:frameworks%2F) which then [only turns off](https://cs.android.com/android/platform/superproject/main/+/main:frameworks/base/services/core/java/com/android/server/pm/InstallPackageHelper.java?q=bypassLowTargetSdkBlock&ss=android%2Fplatform%2Fsuperproject%2Fmain:frameworks%2F) the target API check.

**Comment by hg42** [comment]
thanks for investigating...

Did I say, that I hate that hiding game (in this case Google)...?
What's the purpose to hide something (that a user will never see), when developers can look at the sources?

I now use `pm install --bypass-low-target-sdk-block` and check if the error message complains about (=contains) the option.

That's not directly what I want (checking if it's available), but I think it's more future-proof than using the api version. The fact that it is introduced at that version doesn't mean it will always be there after it.
On the other side, the error behavior might also change.

**Comment by MichaelZ4714** [comment]
I wanted to write this as a feature wish today because I ran into this problem yesterday. Fortunately I had a look onto the issue list before and saw this topic. Thank you that you took care of the problem, I hope thre will be a new release soon. I had to help me using adb install with the above mentioned parameter and restore the data in a second step for the older apps. Fortunately there were only 16, but the complete solution with Neo Backup would have been much easier...
Thanks for your continuous work!!  I could make tests with session installer using a beta release.

**Comment by hg42** [comment]
well, you could have asked.
I would have created a so called "pumpkin" test apk for you (at least, if I have some spare time, are you on the telegram group? I usually post it there).

I added it to the repo.
However, it's just written down and needs testing to be added to the main branch.

**Comment by DJCrashdummy** [comment]
i came here because of the infamous `INSTALL_FAILED_DEPRECTED_SDK_VERSION` error/bug. ...because i always try to use the same NeoBackup version with which the backup was created.

just want to report, after updating to the latest 8.3.6 release it works like a charm on Android 14. :+1:

---

BTW: how about a feauture to schedule not just backups, but also the tasks from the helper/tools section, like deleting old backups resp. backups of not installed apps, saving a list of all apps, exporting all scheduled tasks itself and copying the apk - and overwriting if the same APK already exists (i know, the APK is also in its own backup folder)?
-> sorry for getting a little bit off-topic, but that came into my mind while dealing with this issue.

**Comment by hg42** [comment]
thanks for confirming

you should not mix "issues", this one will be closed and the feature request would not be seen... also discussion about it doesn't belong here.
Feel free to add it as a new issue.

**Comment by hg42** [comment]
fixed
