### ISSUE TITLE
[Bug] HELP PLEASE - can't install "Google" search app (com.google.android.googlequicksearchbox)

### ISSUE THREAD

**Issue by MrEngineerMind** [NeoApplications/Neo-Backup#898]
**Description**
I am using a slightly older version of NeoBackup (8.3.4) and I accidentally uninstalled "Google" on my phone.

When I try to restore it from a neobackup, I get the below error:

![Google-WontInstall](https://github.com/user-attachments/assets/43e6e158-e45f-4e03-b7e4-1be0b8c8c4cb)

**System Information(please complete the following information):**

- Device: Pixel 4a
- Android Version: 10 
- ROM: (AOSP, MIUI, OOS...)  Stock 10 w/Magisk
- App's Version: 8.3.4

**Comment by MrEngineerMind** [comment]
The backup I had was just the APK and nothing else, and when I tried to restore it, I received the above error.

But, I had a spare Pixel4a and did a full backup of the Google app from it (w/data, etc), and I was able to restore it on my main phone and everything is working ok now. I don't know why the APK-only backup didn't work.

"Plus, why using an obsolete version?" - I am from the "If it isn't broken, don't fix it" camp. I tend to wait a while for any surprises to settle down before I upgrade, like the recent "All my backups are not visible" posts of the new version.

**Comment by hg42** [comment]
Google system apps are more complicated than user apps or some simple system apps that only hap[pen to be stored in the system partition.

That's why there are gapps packages.
E.g. these apps are especially written or compiled for each Android version (therefore you have different gapps for each Android version, you can also see it in the version numbers).
I also think, they need some initialization after the install, probably via scripting done in the gapps package.

Not sure what you mean with "uninstalling". System apps cannot be uninstalled in a normal way, so you used a root tool, I guess? Uninstalling means removing the attached data folders. And if installing the apk you don't get them back (e.g. because there is not scripting done).

If you are missing some system app, you should either reinstall your custom ROM, or the gapps package that your ROM uses.
This usually can be done without any problems. But it needs to be the same ROM or gapps that you had before, that is mandatory.

**Comment by hg42** [comment]
Btw. Google apps should not store any important info on the device. It's all in the cloud.
So reinstalling gapps should always work, in the worst case, you need to login again to the Google account.
