### ISSUE TITLE
[Bug] Support for apps using keystore

### ISSUE THREAD

**Issue by yelworc** [NeoApplications/Neo-Backup#96]
**Description/Steps To Reproduce**
The [Bandcamp](https://play.google.com/store/apps/details?id=com.bandcamp.android&hl=en) app cannot be restored correctly from a previous backup.

The source app was logged in to an account, whereas the restored app looks as if it was just installed from scratch. App data _seems_ to have been (partially?) restored, though – at least the app info screen shows a non-zero "User data" size right after restoring.

**Expected behavior**
The restored app should be in the exact same state as when the backup was made.

**System Information**
 - Device: Moto g7 (backup) → Moto g7plus (restore)
 - Android Version: 9 (backup) → 10 (restore)
 - ROM: (AOSP, MIUI, OOS...): LineageOS 16.0 (backup) → LineageOS 17.1 (restore)
 - App's Version: 3.0.0

**Comment by yelworc** [comment]
For the record, Titanium Backup has the exact same problem with this app.

It's not that logging in after restoring is a big issue, but the root cause might affect other apps as well? I'm happy to help investigate further, but I need to know where to look and what to look for :smile:

**Comment by machiav3lli** [comment]
It could be that the app is keeping its credentiales encrypted in the device's keystore which means that a "full" restoration won't be possible. For the record this applies also to Signal.

**Comment by yelworc** [comment]
Ah, that makes sense! A warning/notice icon next to the corresponding entries in OABX would be useful, but probably there's no way to tell "from outside" whether an app is using the device keystore… Feel free to close this, then.

FWIW, so far I've encountered 3 more cases (e.g. GitHub and PinDroid), but the majority of apps apparently _doesn't_ store credentials in the keystore :)

**Comment by Tiefkuehlpizze** [comment]
We should collect those caveats on some FAQ page. Android's Keystore is something we cannot hack (yet?).

**Comment by marcdw1289** [comment]
Yeah, the same with the Matrix app Element (Riot.im). I don't remember if I was able to backup but restoring data definitely failed with oandbackup and Titanium Backup.
Not really a problem for me since I use a password manager.

**Comment by hg42** [comment]
I just read this:
https://www.thecodeside.com/2020/09/14/android-auto-backup-keystore-encryption-broken-heart-love-story/

nothing new, but some interesting points.
Looks like Google Backup cannot backup the keystore files either.
Actually, I think I had to re-login for some apps after restoring Google Backups.

This article also shows, that there can be a lot of different situations.
E.g. the keystore may only contain a password that is used to encrypt some files in the usual app data. Or it may contain actual data. It's left to the programmer's imagination.

This explains, why some apps behave different than others or some weird situations.
E.g. when I usually restore Bitwarden, it has everything in place, but it's password list is empty without reporting any error. I can even sync, so the login may work, but the list remains empty. I have to re-login to get back to normal behavior. Additionally Bitwarden needs to re-allow "autofill" and "draw over other apps" permissions.

Encryption can be dependent on several conditions, e.g. device specific IDs (Android ID? hardware?), user and app specific keys or user inputs/settings. So restoring such a file will only work, if the appropriate conditions are still met.

Some conditions might eventually be restored. E.g. Titanium Backup had/has(?) the ability to restore the Android ID, which worked for several cases in the past. Not sure if this would still help, I didn't use that feature for a few years, because I usually only use <5 apps with such problems.

**Comment by Atrate** [comment]
This issue (https://github.com/MuntashirAkon/AppManager/issues/82) might come in handy, as @MuntashirAkon is actively working on the same thing, with progress summarized in https://github.com/MuntashirAkon/AppManager/issues/82#issuecomment-696296631

**Comment by bengalih** [comment]
Netflix is another one that never seems to restore credentials.  I can't test on TiBu anymore because SAPK.

**Comment by hg42** [comment]
you can use SAI to restore the app and TiBu to restore only the data.
Or use clear data and restore data with TiBu.
It would also be nice to see, if it makes a difference to uninstall the whole app or clear data alone.

**Comment by avently** [comment]
Guys, found a solution
https://community.signalusers.org/t/wiki-howto-manual-backup-restore-if-full-backup-does-not-work/2462

Probably can be implemented in OAndBackupX.

**Comment by machiav3lli** [comment]
No solution for this in the foreseeable future
